 innok_heros_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
 
 innok_heros_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['joint_base_wheel_front_left', 'joint_base_wheel_rear_left']
  right_wheel: ['joint_base_wheel_front_right', 'joint_base_wheel_rear_right']
  publish_rate: 100
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.25
 
  # Base frame_id
  base_frame_id: base_link
 
  enable_odom_tf: true
 
  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 2.2
  wheel_radius_multiplier    : 1.0
 
  # Velocity and acceleration limits
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0   # rad/s^2
